// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: proto/currency_convert.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CurrencyConvertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount       float32 `protobuf:"fixed32,1,opt,name=amount,proto3" json:"amount,omitempty"`
	FromCurrency string  `protobuf:"bytes,2,opt,name=fromCurrency,proto3" json:"fromCurrency,omitempty"`
	ToCurrency   string  `protobuf:"bytes,3,opt,name=toCurrency,proto3" json:"toCurrency,omitempty"`
}

func (x *CurrencyConvertRequest) Reset() {
	*x = CurrencyConvertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_currency_convert_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrencyConvertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyConvertRequest) ProtoMessage() {}

func (x *CurrencyConvertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_convert_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyConvertRequest.ProtoReflect.Descriptor instead.
func (*CurrencyConvertRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_convert_proto_rawDescGZIP(), []int{0}
}

func (x *CurrencyConvertRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CurrencyConvertRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *CurrencyConvertRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

type CurrencyConvertResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount float32 `protobuf:"fixed32,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *CurrencyConvertResponse) Reset() {
	*x = CurrencyConvertResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_currency_convert_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrencyConvertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyConvertResponse) ProtoMessage() {}

func (x *CurrencyConvertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_convert_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyConvertResponse.ProtoReflect.Descriptor instead.
func (*CurrencyConvertResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_convert_proto_rawDescGZIP(), []int{1}
}

func (x *CurrencyConvertResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_proto_currency_convert_proto protoreflect.FileDescriptor

var file_proto_currency_convert_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x5f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x74, 0x0a, 0x16, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66,
	0x72, 0x6f, 0x6d, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x74,
	0x6f, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x74, 0x6f, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x31, 0x0a, 0x17, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x62,
	0x0a, 0x16, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x74, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_currency_convert_proto_rawDescOnce sync.Once
	file_proto_currency_convert_proto_rawDescData = file_proto_currency_convert_proto_rawDesc
)

func file_proto_currency_convert_proto_rawDescGZIP() []byte {
	file_proto_currency_convert_proto_rawDescOnce.Do(func() {
		file_proto_currency_convert_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_currency_convert_proto_rawDescData)
	})
	return file_proto_currency_convert_proto_rawDescData
}

var file_proto_currency_convert_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_currency_convert_proto_goTypes = []interface{}{
	(*CurrencyConvertRequest)(nil),  // 0: proto.CurrencyConvertRequest
	(*CurrencyConvertResponse)(nil), // 1: proto.CurrencyConvertResponse
}
var file_proto_currency_convert_proto_depIdxs = []int32{
	0, // 0: proto.CurrencyConvertService.Convert:input_type -> proto.CurrencyConvertRequest
	1, // 1: proto.CurrencyConvertService.Convert:output_type -> proto.CurrencyConvertResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_currency_convert_proto_init() }
func file_proto_currency_convert_proto_init() {
	if File_proto_currency_convert_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_currency_convert_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrencyConvertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_currency_convert_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrencyConvertResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_currency_convert_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_currency_convert_proto_goTypes,
		DependencyIndexes: file_proto_currency_convert_proto_depIdxs,
		MessageInfos:      file_proto_currency_convert_proto_msgTypes,
	}.Build()
	File_proto_currency_convert_proto = out.File
	file_proto_currency_convert_proto_rawDesc = nil
	file_proto_currency_convert_proto_goTypes = nil
	file_proto_currency_convert_proto_depIdxs = nil
}
